### ISSUE TITLE
"skipLabels" doesn't work properly in PRs from forked repos

### ISSUE THREAD

**Issue by kwin** [dangoslen/changelog-enforcer#176]
Although a proper skip label is set (e.g. in https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2756), it is not evaluated, i.e. the changelog enforcer is not skipped.
Not sure if this related to using the event "pull_request_target" or missing permissions (https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/77104988d6971e7d43aa973f859bcdf5a9596f25/.github/workflows/maven.yml#L16).

**Comment by dangoslen** [comment]
I'll need to take a deeper look at how this action works with forks. I know it has been a pain point for other actions. 

I did look at that PR you linked, however, and I don't see a `labeled` action type in your `pull_request_target` event type. Consider adding that?

**Comment by dangoslen** [comment]
@kwin apologies for getting back to this late, but did you try adding the `labeled` action in your workflow to see if that resolved your issue?

**Comment by kwin** [comment]
I tried adding a commit after setting the label and it still your step didn't detect it. So this issue is not related to the action type.

**Comment by dangoslen** [comment]
Ok. I'll keep digging then.

**Comment by kwin** [comment]
Maybe related to the fact that I use event `pull_request_target` (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target)

**Comment by dangoslen** [comment]
@kwin I double-checked  your PR again - did you ever attempt to update the event types for the `pull_request_target` to include `labeled,unlabeled` events?

**Comment by kwin** [comment]
No, but once again, the event was fired due to a subsequent commit and even then the label was not detected.
