### ISSUE TITLE
add support for `push` events

### ISSUE THREAD

**Issue by Serpentiel** [dangoslen/changelog-enforcer#210]
**Is your feature request related to a problem? Please describe.**
currently, `push` event isn't supported

**Describe the solution you'd like**
implement support for `push` event

**Describe alternatives you've considered**
n/a

**Additional context**
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push

**Comment by Serpentiel** [comment]
hey, thank you for your response!

having it trigger on `push` will be helpful to determine whether the changelog entry is missing in the branch before opening a PR

**Comment by dangoslen** [comment]
Thanks for explaining your use case.

I don't think the value added is worth the complexity of adding it. If you want to open a PR to add this yourself, I'm happy to take a look though!

**Comment by dangoslen** [comment]
@Serpentiel - I'm going to close this issue for now. 

If you want to open a PR to add this functionality - I'd be happy to review it and get it added!
