### ISSUE TITLE
skipLabel is not respected on reruns of the action

### ISSUE THREAD

**Issue by mplorentz** [dangoslen/changelog-enforcer#211]
**Describe the bug**
Adding the `skipLabel` to a PR after the changelog-enforcer action has failed once doesn't cause subsequent reruns of the action to succeed.

**To Reproduce**
1. Feel free to fork [our repo](https://github.com/planetary-social/planetary-ios) and create a dummy PR that doesn't update the changelog.
2. Wait for the "Check CHANGELOG" action to fail.3. 
3. Add the `Skip-Changelog` label to the PR.
4. Rerun the Check CHANGELOG action. 

**Expected behavior**
The Check CHANGELOG action succeeds.

**A link to or sample of your workflow**
[Here](https://github.com/planetary-social/planetary-ios/blob/main/.github/workflows/main.yml) is our workflow and [here](https://github.com/planetary-social/planetary-ios/pull/774) is an example of a PR exhibiting this bug.

**Comment by dangoslen** [comment]
Hi @mplorentz! Sorry for the delay. I just got back from a vaction.

Looking at your action workflow, you are missing the specific `labeled` and `unlabeled` action types. See the specifics (especially the notes) on the [`pull_request` event details](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request)

Do you think we need to update the [useage](https://github.com/dangoslen/changelog-enforcer#usage) section to make it more clear?

**Comment by mplorentz** [comment]
Ah, thanks so much for taking a look! Adding the `labeled` and `unlabeled` types fixed it for me. I think the usage section is clear enough, I just skimmed it the first time around :) and anyone else who runs into this problem will hopefully find this issue. Thanks for your work on this, it's been a really nice addition to our CI!
