### ISSUE TITLE
Enforce updated changelog per-directory

### ISSUE THREAD

**Issue by 7596ff** [dangoslen/changelog-enforcer#212]
**Is your feature request related to a problem? Please describe.**
My project includes multiple crates in a workspace, each with separate changelogs.

**Describe the solution you'd like**
I'd like for there to be a `match` key that accepts a directory to search for changes in, alongside the `changeLogPath` key.

**Describe alternatives you've considered**
I've tried to use this in a reusable workflow, but I can not get the action to only run in a subdirectory, since those check out their own sources.

**Comment by dangoslen** [comment]
Hi @7596ff! 

🤔 Any reason to not have multiple invocations of the changelog enforcer in your workflow for each path?

**Comment by dangoslen** [comment]
Hi @7596ff 

I'm going to close this for now as I haven't heard from you. Please let me know if running multiple steps/invocations of the changelog enforcer doesn't work for you!
