### ISSUE TITLE
Does not work with checkout@v2

### ISSUE THREAD

**Issue by mathomp4** [dangoslen/changelog-enforcer#25]
**Describe the bug**

This might not be a bug, but an FYI. I accidentally typed:
```yaml
    - uses: actions/checkout@v2
```
when adding this to a repo I help manage and this action is not happy (at 1.2.0). Not sure why. 

**To Reproduce**
Try to use with `actions/checkout@v2`, and Github throws an error

**Expected behavior**
The behavior with `actions/checkout@v1` saying you need to change the Changelog.

(NOTE: This might be also be due to my repo? Not sure...)

**Comment by dangoslen** [comment]
Hey @mathomp4 - do you have a public link to the action logs? If not, could you supply output of the `changelog-enforcer` action?

Thanks for opening the issue!

**Comment by mathomp4** [comment]
@dangoslen Huh. Maybe? I fixed it back to v1 after I saw it. Let me go see...

Does this work: https://github.com/GEOS-ESM/MAPL/runs/1114113276?check_suite_focus=true

Weirdly it was the:
```
/usr/bin/git diff origin/develop --name-status --diff-filter=AM
fatal: ambiguous argument 'origin/develop': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
##[error]The process '/usr/bin/git' failed with exit code 128
```
error.

I tried it on my command line and it worked and that's when I figured it was my change to v2.

**Comment by mathomp4** [comment]
Happy as a clam with v1:

https://github.com/GEOS-ESM/MAPL/runs/1114130479?check_suite_focus=true

**Comment by mathomp4** [comment]
And in case permissions don't let you see what you need, let me know and I'll try and get the raw logs.

**Comment by dangoslen** [comment]
Nope that is perfect.

I think the issue is that in `v2`, it no longer checks out the code in a detached head state but as a branch.

I'll look into this and see what I can figure out over the weekend - I don't have a ton of time before then, unfortunately.

**Comment by mathomp4** [comment]
> Nope that is perfect.
> 
> I think the issue is that in `v2`, it no longer checks out the code in a detached head state but as a branch.
> 
> I'll look into this and see what I can figure out over the weekend - I don't have a ton of time before then, unfortunately.

Not a big issue for me. I've been looking for something like this action to be strict with changelogs, so I'm glad it works even with v1. (Now watch, using v2 breaks v1 compatibility and hello v2.0.0 😄 )

**Comment by dangoslen** [comment]
@mathomp4 I believe I have fixed this issue. 

Can you try running again using `actions/checkout@v2` and `dangoslen/changelog-enforcer@49dd3f6 `? That will help serve as a smoke test before actually creating the release.

**Comment by mathomp4** [comment]
@dangoslen You seem to have done it. I think it worked with both `actions/checkout@v1` and `actions/checkout@v2` at least in my test-things-out-repo. Thanks!

Now if only I knew enough JavaScript to figure out how you fixed it! 😄

**Comment by dangoslen** [comment]
haha. Honestly, it is more `git` knowledge than anything else. 

In v2, they only download the commit needed instead of the entire repository to improve download and run time. Just needed to download the extra branch to do the `git diff` to check for a change to the changelog.

Thanks again for opening this issue and confirming! I'll be cutting an official `v1.4.0` release later today

**Comment by mathomp4** [comment]
> haha. Honestly, it is more `git` knowledge than anything else.
> 
> In v2, they only download the commit needed instead of the entire repository to improve download and run time. Just needed to download the extra branch to do the `git diff` to check for a change to the changelog.

Ahh. Well it did seem faster though with GitHub Actions that varies so much you never know!
