### ISSUE TITLE
Enforce changelog updates when certain labels are applied

### ISSUE THREAD

**Issue by gmarciani** [dangoslen/changelog-enforcer#277]
**Is your feature request related to a problem? Please describe.**
I'd like to skip the changelog enforcement when some labels are applied and some other are not.
Example: there may be cases where a PR contains a mix of changes that require changelog updates and changes that do not. In this case the Pr would contain a mix of labels that would enforce changelog updates and some that would not.

**Describe the solution you'd like**
Add a new field "includeLabels" accepting a comma separated list of labels.

**Comment by dangoslen** [comment]
Hi @gmarciani 

I believe this feature already exists to a degree. You can use the `skipLabels` input outlined in the [README](https://github.com/dangoslen/changelog-enforcer?tab=readme-ov-file#skiplabels). Are you suggesting it needs to be complex that what is described with that input?


Note: please remember to include the `labeled` and `unlabeled` [action types](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request)
