### ISSUE TITLE
Validate the Changelog Format Is Correct

### ISSUE THREAD

**Issue by dangoslen** [dangoslen/changelog-enforcer#32]
**Describe the solution you'd like**
This action currently only makes sure that the file specified has changed. However, it would be useful to validate a few things about the changelog such that it conforms to standards or formats already known.

The most common is [Keep a Changelog](https://keepachangelog.com/en/1.0.0/). However, I know other teams have used this with simplified formats, so they would need to be able to skip validation or provide their own validate...

To me, focusing on minimal format is important. [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) itself is more a convention over a standard. Teams should be able to add details they believe are relevant to their changelog as needed.

**Describe alternatives you've considered**
An alternative could be providing output from the changelog to the caller to be verified by their own script. Perhaps a combination of both this and the previous are good approaches? 

**Additional context**
Being able to validate that changelog could be important, but it could easily become burdensome.

**Comment by anmlnath** [comment]
Looks like https://github.com/mindsers/changelog-reader-action is taking on this task.

**Comment by dangoslen** [comment]
Thanks for the info @anmlnath!
