### ISSUE TITLE
Make error message customizable

### ISSUE THREAD

**Issue by renedupont** [dangoslen/changelog-enforcer#62]
**Is your feature request related to a problem? Please describe.**
While the check already has a pretty clear error message `(Error: No update to CHANGELOG.md found!)` I'd like to customize it. In my use case I also want to let other contributors know what the expectation is by e.g. adding a link to keep a changelog to the error message or something alike.

**Describe the solution you'd like**
I'd like to have an additional param next to skipLabels etc. to customize the error message and have the current message as the default in case it was not set.

**Describe alternatives you've considered**
Alternatively I added a follow up action step to the workflow that echo's that message if the check fails but that feels like a painful workaround.

**Comment by dangoslen** [comment]
This sounds like a great idea! Thank you for the suggestion. 

I like the idea of adding a custom message and also set the error message as an output variable as well. That way, you could combine it with other actions to customize your workflow even further (ie adding it as a comment, or including it in some message to Slack/email etc.) 

I'll work on this over the weekend - but I am also happy to accept a pull request if you would like to try it yourself!

**Comment by renedupont** [comment]
Cool! I am just getting into github actions and have no js experience, but if you can't find the time I'll be happy to try it myself at some point in the near future 👍🏻

**Comment by dangoslen** [comment]
@renedupont if you want to take a look at the changes, you can take a look at #69.

I am planning to release this in conjunction with a breaking change to make Changelog Enforcer v2. I am planning to wait till the new year to release simply to allow people some time to upgrade to the latest v1 version.

**Comment by dangoslen** [comment]
This is now in [v2.0.0](https://github.com/dangoslen/changelog-enforcer/releases/tag/v2.0.0)
